#!/bin/bash
echo "=> Building multi-arch (amd64 & arm64) for branch: $SOURCE_BRANCH"

docker buildx create --name mybuilder --use
docker run --rm --privileged multiarch/qemu-user-static --reset -p yes

# 두 아키텍처를 동시에 빌드하고 하나의 태그($IMAGE_NAME)로 푸시합니다.
docker buildx build --platform linux/amd64,linux/arm64 -f $DOCKERFILE_PATH -t $IMAGE_NAME --push .
