#!/usr/bin/env bash
set -euo pipefail

report_json="${1:-lifecycle-reports/php-lifecycle.json}"
report_md="${2:-lifecycle-reports/php-lifecycle.md}"
repo="${GITHUB_REPOSITORY:-woosungchoi/fpm-alpine}"
: "${GH_TOKEN:?GH_TOKEN is required}"
[ -f "$report_json" ] && [ -f "$report_md" ] || { echo "lifecycle report files are required" >&2; exit 64; }

state="$(python3 - "$report_json" <<'PY'
import json,sys
p=json.load(open(sys.argv[1]))
if p.get('eolReached') or p.get('mismatches'): print('mismatch')
elif p.get('upstreamUnavailable'): print('upstream-unavailable')
elif any(r.get('state','').startswith('warning-') for r in p.get('records',[])): print('warning')
else: print('ok')
PY
)"
[ "$state" != ok ] || { echo "no lifecycle issue needed"; exit 0; }
label="php-lifecycle"
title="PHP lifecycle attention required"
gh label create "$label" --repo "$repo" --color "d93f0b" --description "PHP lifecycle or upstream-source attention" >/dev/null 2>&1 || true
existing="$(gh issue list --repo "$repo" --state open --label "$label" --search "in:title $title" --json number --jq '.[0].number // empty')"
body="$(mktemp)"
trap 'rm -f "$body"' EXIT
{
  echo "Lifecycle state: **$state**"
  echo
  cat "$report_md"
  echo
  echo "Generated by \`php-lifecycle\`; update source metadata only through a reviewed PR."
} > "$body"
if [ -n "$existing" ]; then
  gh issue comment "$existing" --repo "$repo" --body-file "$body" >/dev/null
  echo "updated existing lifecycle issue #$existing"
else
  gh issue create --repo "$repo" --title "$title" --label "$label" --body-file "$body"
fi
